
#ifndef MMN_14_ERRORS_H
#define MMN_14_ERRORS_H

typedef enum e_RESULT
{
    FAILURE_NUMBER_TOO_BIG,
    FAILURE_MISSING_OPERAND,
    FAILURE_NOT_A_LEGAL_NUMBER,
    FAILURE_NOT_A_LEGAL_STRING,
    EXTERN_DOESNT_REFERENCE_A_DEFINED_SYMBOL,
    ILLEGAL_ADDRESSING_MODE,
    ILLEGAL_COMMA_IN_BEGINNING_OR_END_OF_SENTENCE,
    ILLEGAL_NUMBER_OF_COMMAS_BETWEEN_NUMBERS,
    ILLEGAL_OPERAND_TO_ADDRESSING_MODE,
    ERROR_NOT_AN_EXISTING_LABEL,
    ERROR_TRYING_TO_ADD_EXISTING_SYMBOL,
    ERROR_TRYING_TO_ADD_RESERVED_WORD,
    ENTRY_DOESNT_REFERENCE_A_DEFINED_SYMBOL,
    EXTERN_CANNOT_HAVE_A_LABEL,
    ENTRY_CANNOT_HAVE_A_LABEL,
    ILLEGAL_LABEL,
    ERROR_ILLEGAL_STRING_DECLARATION,
    ERROR_IN_COMMAND_TRANSLATION,
    ERROR_ILLEGAL_DATA_DECLARATION,
    ILLEGAL_NUMERIC_STRING,
    NO_SPACE_OR_TAB_BEFORE_COMMAND,
    ERROR_ILLEGAL_REGISTER,
    ERROR_EXTRACTING_EXTERN_OR_ENTRY_SYMBOLS,
    SUCCESS
} RESULT;



#endif
